# Generated by Django 5.2.14 on 2026-08-29 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cadastro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "criado",
                    models.DateTimeField(
                        auto_now_add=True, help_text="A hora em que o objeto foi criado.", verbose_name="created"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="A hora em que o objeto foi modificado pela última vez.",
                        verbose_name="modificado",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text="Uma descrição para o cadastro. Nome ou Razão Social.",
                        max_length=255,
                        unique=True,
                        verbose_name="descrição",
                    ),
                ),
                (
                    "tipo_pessoa",
                    models.CharField(
                        choices=[("F", "Pessoa Física"), ("J", "Pessoa Jurídica")],
                        default="F",
                        help_text="O tipo de pessoa para este cadastro.",
                        max_length=1,
                        verbose_name="tipo de pessoa",
                    ),
                ),
                (
                    "cliente",
                    models.BooleanField(
                        default=False, help_text="Indica se este cadastro é um cliente.", verbose_name="cliente"
                    ),
                ),
                (
                    "fornecedor",
                    models.BooleanField(
                        default=False, help_text="Indica se este cadastro é um fornecedor.", verbose_name="fornecedor"
                    ),
                ),
                (
                    "transportadora",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se este cadastro é uma transportadora.",
                        verbose_name="transportadora",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True, help_text="Indica se este cadastro está ativo.", verbose_name="ativo"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(
                        blank=True, help_text="Observações adicionais sobre este cadastro.", verbose_name="observação"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="O usuário que registrou este cadastro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "cadastro",
                "verbose_name_plural": "cadastros",
                "ordering": ["descricao"],
            },
        ),
    ]
